#!/bin/bash

yay -S libdbusmenu-glib \
	libdbusmenu-gtk3 \
	libdbusmenu-gtk2 \
	appmenu-gtk-module-git \
	vala-panel-appmenu-xfce-git \
	vala-panel-appmenu-registrar-git \
    --noconfirm

xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true
xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true
