#!/bin/bash

sudo pacman -S plank compton dunst lxappearance-obconf menumaker obconf obconf-qt oblogout openbox rofi wireless_tools mpd network-manager-applet xscreensaver --noconfirm

yaourt -S polybar cava arc-icon-theme-git brightnessctl openbox-arc-git obmenu-generator --noconfirm
