#!/bin/bash

sudo pacman -S plank compton dunst lxappearance-obconf menumaker obconf obconf-qt obmenu oblogout openbox openbox-themes rofi wireless_tools mpd powerline powerline-fonts python-powerline network-manager-applet xscreensaver --noconfirm

yaourt -S polybar cava arc-icon-theme-git backlight-git brightnessctl dunst-git moka-icon-theme-git openbox-arc-git obmenu-generator --noconfirm
