#!/bin/bash

pacman -Sy reflector --noconfirm;

reflector -l 2 -c sg --save /etc/pacman.d/mirrorlist;

mount /dev/nvme0n1p5 /mnt;
mkdir /mnt/boot;
mount /dev/nvme0n1p3 /mnt/boot;

pacstrap -i /mnt \
  base \
  base-devel \
  git \
  curl \
  wget \
  vim \
  nano \
  networkmanager \
  grub \
  efibootmgr \
  linux-headers \
  linux-lts \
  linux-lts-headers \
  linux-zen \
  linux-zen-headers \
  linux-firmware \
  python \
  openssh \
  ansible \
  --noconfirm;
  
exec genfstab -Up /mnt >> /mnt/etc/fstab