#!/bin/bash

pacman -Sy reflector --noconfirm &
pacstrap -i /mnt \
  base \
  base-devel \
  vim \
  nano \
  networkmanager \
  grub \
  efibootmgr \
  linux-headers \
  linux-lts \
  linux-lts-headers 
  linux-zen \
  linux-zen-headers \
  linux-firmware \
  --noconfirm &
  
genfstab -Up /mnt >> /mnt/etc/fstab