#!/bin/bash
yay -S la-capitaine-icon-theme osx-el-capitan-theme-git capitaine-cursors --noconfirm

sudo pacman -S gtk-engine-murrine gtk-engines sassc --noconfirm

cd /tmp && git clone https://github.com/vinceliuice/Mojave-gtk-theme.git && cd Mojave-gtk-theme && sudo ./install.sh -a && cd ..
git clone https://github.com/vinceliuice/McMojave-circle.git && cd McMojave-circle && sudo ./install.sh -a && cd ~